// Glosario de métricas del panel. Es la ÚNICA fuente de definiciones: lo usan los botones «i» de cada indicador
// y la pestaña «Glosario». Todo está escrito en términos genéricos de negocio, sin referencias a un caso concreto.
export type Metric = { nombre: string; grupo: string; def: string; formula: string; fuente: string; donde: string };

export const GRUPOS = ['Ventas', 'Clientes', 'Marketing', 'Producto', 'Operaciones', 'Devoluciones', 'Promociones'] as const;

export const M: Record<string, Metric> = {
  // ------------------------------------------------------------------ Ventas
  ventas: { nombre: 'Ventas', grupo: 'Ventas', def: 'Ingreso por producto de los pedidos no cancelados (entregados, pendientes y devueltos), sin impuestos ni envío. Cuentan todas las fichas del catálogo, activas o no, porque su venta se cobró. Los cancelados no son venta.', formula: 'Σ subtotal de pedidos no cancelados', fuente: 'Pedidos', donde: 'Resumen, Ventas' },
  ventas_netas: { nombre: 'Ventas netas', grupo: 'Ventas', def: 'Cifra de referencia del panel: ventas una vez descontado lo reembolsado (devoluciones totales y parciales). Los importes no reflejan ningún descuento de código; como sensibilidad se muestra la cifra si se hubiera aplicado.', formula: 'Ventas − Σ reembolsos', fuente: 'Pedidos, devoluciones', donde: 'Resumen, Ventas, Operaciones' },
  facturacion: { nombre: 'Facturación total', grupo: 'Ventas', def: 'Importe total cobrado al cliente, incluyendo impuestos y envío.', formula: 'Σ total del pedido', fuente: 'Pedidos', donde: 'Ventas' },
  impuestos: { nombre: 'Impuestos', grupo: 'Ventas', def: 'Impuestos repercutidos en los pedidos. No forman parte de las ventas.', formula: 'Σ impuestos del pedido', fuente: 'Pedidos', donde: 'Ventas' },
  envios: { nombre: 'Ingresos por envío', grupo: 'Ventas', def: 'Gastos de envío cobrados al cliente. No forman parte de las ventas.', formula: 'Σ envío del pedido', fuente: 'Pedidos', donde: 'Ventas' },
  pedidos: { nombre: 'Pedidos', grupo: 'Ventas', def: 'Número de pedidos no cancelados de la selección. Un pedido puede incluir varios productos.', formula: 'Recuento de pedidos', fuente: 'Pedidos', donde: 'Resumen, Ventas' },
  unidades: { nombre: 'Unidades vendidas', grupo: 'Ventas', def: 'Número de productos vendidos (cada unidad cuenta, aunque estén en el mismo pedido).', formula: 'Σ cantidad de las líneas', fuente: 'Líneas de pedido', donde: 'Resumen, Ventas, Producto' },
  ticket: { nombre: 'Ticket medio', grupo: 'Ventas', def: 'Ventas medias por pedido (AOV, valor medio del pedido).', formula: 'Ventas ÷ Pedidos', fuente: 'Pedidos', donde: 'Resumen, Ventas' },
  upt: { nombre: 'Unidades por pedido', grupo: 'Ventas', def: 'Cuántos productos lleva de media cada pedido (UPT). Mide la capacidad de vender más en una compra.', formula: 'Unidades ÷ Pedidos', fuente: 'Pedidos, líneas', donde: 'Ventas' },
  precio_medio: { nombre: 'Precio medio por unidad', grupo: 'Ventas', def: 'Precio medio al que se vende cada producto (ASP), después de descuentos.', formula: 'Ventas de producto ÷ Unidades', fuente: 'Líneas de pedido', donde: 'Ventas, Producto' },
  ventas_dia: { nombre: 'Ventas por día', grupo: 'Ventas', def: 'Ritmo diario de ventas del periodo. Permite comparar periodos de distinta duración.', formula: 'Ventas ÷ Días del periodo', fuente: 'Pedidos', donde: 'Ventas' },
  variacion: { nombre: 'Variación vs periodo anterior', grupo: 'Ventas', def: 'Cambio porcentual frente a un periodo de igual duración inmediatamente anterior al seleccionado. Solo aparece si hay datos para ese periodo.', formula: '(Actual − Anterior) ÷ Anterior', fuente: 'Pedidos', donde: 'Resumen, Ventas' },

  // ------------------------------------------------------------------ Clientes
  registrados: { nombre: 'Clientes registrados', grupo: 'Clientes', def: 'Personas registradas hasta el final del periodo, según el país declarado en el registro. Las cuentas con el mismo usuario de email (lo que va antes de la @) son una persona.', formula: 'Recuento de clientes con alta ≤ fin del periodo', fuente: 'Clientes', donde: 'Clientes' },
  altas: { nombre: 'Altas del periodo', grupo: 'Clientes', def: 'Cuentas creadas dentro del periodo seleccionado.', formula: 'Recuento de clientes con alta dentro del periodo', fuente: 'Clientes', donde: 'Clientes' },
  compradores: { nombre: 'Compradores', grupo: 'Clientes', def: 'Personas distintas con al menos un pedido no cancelado dentro de la selección. Las cuentas con el mismo usuario de email se cuentan como una persona.', formula: 'Personas distintas con pedido no cancelado', fuente: 'Pedidos', donde: 'Resumen, Clientes' },
  conversion: { nombre: 'Conversión a comprador', grupo: 'Clientes', def: 'Qué parte de los registrados ha comprado alguna vez (hasta el fin del periodo).', formula: 'Registrados que han comprado ÷ Registrados', fuente: 'Clientes, pedidos', donde: 'Clientes' },
  nuevos: { nombre: 'Clientes nuevos', grupo: 'Clientes', def: 'Personas cuyo primer pedido válido y no cancelado cae dentro del periodo. El canal de ese pedido es su canal de captación.', formula: 'Recuento de primeros pedidos válidos', fuente: 'Pedidos', donde: 'Resumen, Clientes' },
  recurrentes: { nombre: 'Compradores recurrentes', grupo: 'Clientes', def: 'Compradores con dos o más pedidos no cancelados dentro de la selección.', formula: 'Compradores con ≥ 2 pedidos', fuente: 'Pedidos', donde: 'Clientes' },
  recompra: { nombre: 'Tasa de recompra', grupo: 'Clientes', def: 'Proporción de compradores que repiten dentro de la selección.', formula: 'Compradores recurrentes ÷ Compradores', fuente: 'Pedidos', donde: 'Clientes' },
  pedidos_comprador: { nombre: 'Pedidos por comprador', grupo: 'Clientes', def: 'Frecuencia de compra media: cuántos pedidos hace cada comprador en el periodo.', formula: 'Pedidos no cancelados ÷ Compradores', fuente: 'Pedidos', donde: 'Clientes' },
  gasto_comprador: { nombre: 'Ventas por comprador', grupo: 'Clientes', def: 'Valor medio que aporta cada comprador en el periodo (aproximación al valor de vida del cliente).', formula: 'Ventas ÷ Compradores', fuente: 'Pedidos', donde: 'Clientes' },
  tiempo_primera: { nombre: 'Tiempo hasta la primera compra', grupo: 'Clientes', def: 'Días entre el alta y el primer pedido válido. Se muestra la mediana, que no se distorsiona con casos extremos.', formula: 'Mediana de (primer pedido − alta)', fuente: 'Clientes, pedidos', donde: 'Clientes' },
  concentracion_clientes: { nombre: 'Concentración de clientes', grupo: 'Clientes', def: 'Peso de los 10 mayores compradores en las ventas. Una cifra alta indica dependencia de pocos clientes.', formula: 'Ventas de los 10 mayores compradores ÷ Ventas', fuente: 'Pedidos', donde: 'Clientes' },

  // ------------------------------------------------------------------ Marketing
  inversion: { nombre: 'Inversión', grupo: 'Marketing', def: 'Gasto en marketing de los canales con inversión registrada dentro del periodo, en euros.', formula: 'Σ gasto diario por canal', fuente: 'Gasto de marketing', donde: 'Marketing' },
  ventas_pago: { nombre: 'Ventas de canales de pago', grupo: 'Marketing', def: 'Ventas atribuidas a los canales que tienen inversión registrada.', formula: 'Σ ventas de pedidos de canales con inversión', fuente: 'Pedidos, gasto', donde: 'Marketing' },
  cpa: { nombre: 'Coste por pedido (CPA)', grupo: 'Marketing', def: 'Cuánto cuesta de media conseguir un pedido en canales de pago.', formula: 'Inversión ÷ Pedidos de canales de pago', fuente: 'Pedidos, gasto', donde: 'Marketing' },
  iec: { nombre: 'Índice de Eficiencia de Canal (IEC)', grupo: 'Marketing', def: 'Venta neta atribuida al canal entre su inversión (nota de dirección 1). Incluye la recompra de clientes que captó otro canal: solo el 18,4 % de los pedidos repetidos entra por el canal de captación. Se muestra como referencia: no conviene usarlo para repartir el presupuesto.', formula: 'Venta neta atribuida ÷ Inversión', fuente: 'Pedidos, gasto', donde: 'Marketing' },
  cac: { nombre: 'Coste por cliente nuevo (CAC)', grupo: 'Marketing', def: 'Cuánto cuesta de media captar un cliente nuevo: gasto entre las personas cuyo primer pedido llegó por ese canal. Junto con el retorno de captación, es la métrica de referencia para comparar canales (desde marzo).', formula: 'Inversión ÷ Clientes nuevos captados por el canal', fuente: 'Pedidos, gasto', donde: 'Marketing' },
  retorno_captacion: { nombre: 'Retorno de captación', grupo: 'Marketing', def: 'Venta neta que hacen en sus primeros 90 días los clientes nuevos de un canal, por cada euro invertido. El valor a 90 días es la media de su país (captados del 1-feb al 13-abr). En la propuesta de presupuesto se toma 2 como referencia orientativa.', formula: 'Σ venta neta a 90 días esperada de los clientes nuevos ÷ Inversión', fuente: 'Pedidos, gasto', donde: 'Marketing' },
  valor_90d: { nombre: 'Venta neta a 90 días', grupo: 'Clientes', def: 'Venta neta media de un cliente nuevo en sus primeros 90 días, incluido el primer pedido. Solo con clientes que ya tienen 90 días observables (captados hasta el 13 de abril).', formula: 'Media de Σ venta neta de la persona hasta 90 días después de su primer pedido', fuente: 'Pedidos', donde: 'Marketing' },
  cuota_ventas: { nombre: 'Cuota de ventas', grupo: 'Marketing', def: 'Peso de un canal en las ventas atribuidas a canales de pago. No indica qué canal capta mejor: casi toda la venta atribuida es recompra.', formula: 'Ventas del canal ÷ Ventas de canales de pago', fuente: 'Pedidos', donde: 'Marketing' },
  cuota_gasto: { nombre: 'Cuota de inversión', grupo: 'Marketing', def: 'Peso de un canal en la inversión total de canales de pago.', formula: 'Inversión del canal ÷ Inversión total', fuente: 'Gasto de marketing', donde: 'Marketing' },
  pct_ventas_pago: { nombre: 'Peso de canales de pago', grupo: 'Marketing', def: 'Qué parte de las ventas viene de canales con inversión, frente a canales sin inversión (orgánico, directo, etc.).', formula: 'Ventas de canales de pago ÷ Ventas', fuente: 'Pedidos', donde: 'Marketing' },

  // ------------------------------------------------------------------ Producto
  ventas_producto: { nombre: 'Ventas de producto', grupo: 'Producto', def: 'Ventas calculadas desde las líneas de pedido (cantidad × precio cobrado). Coincide con las ventas del panel.', formula: 'Σ cantidad × precio cobrado', fuente: 'Líneas de pedido', donde: 'Producto' },
  descuento_medio: { nombre: 'Descuento medio sobre tarifa', grupo: 'Producto', def: 'Cuánto por debajo del precio de catálogo se ha vendido de media. Un valor alto indica que la tarifa no refleja el precio real.', formula: '1 − Ventas ÷ Σ (cantidad × tarifa)', fuente: 'Líneas de pedido, catálogo', donde: 'Producto, Promociones' },
  productos_con_ventas: { nombre: 'Productos con ventas', grupo: 'Producto', def: 'Cuántos productos del catálogo han vendido alguna unidad en la selección.', formula: 'Productos con unidades > 0 ÷ Productos del catálogo', fuente: 'Líneas, catálogo', donde: 'Producto' },
  concentracion_productos: { nombre: 'Concentración de producto (Pareto)', grupo: 'Producto', def: 'Peso del 20 % de productos más vendidos en las ventas. Cuanto más alto, más depende el negocio de pocas referencias.', formula: 'Ventas del 20 % de productos con más ventas ÷ Ventas', fuente: 'Líneas de pedido', donde: 'Producto' },
  valoracion: { nombre: 'Valoración media', grupo: 'Producto', def: 'Nota media de las reseñas publicadas en el periodo (solo primer semestre), de 1 a 5. Entre productos solo se compara con 10 o más reseñas, y no anticipa la devolución.', formula: 'Σ valoraciones ÷ Nº de reseñas', fuente: 'Reseñas', donde: 'Producto' },
  resenas: { nombre: 'Reseñas', grupo: 'Producto', def: 'Número de reseñas publicadas en el periodo. Con pocas reseñas, la media de un producto no es fiable.', formula: 'Recuento de reseñas', fuente: 'Reseñas', donde: 'Producto' },
  pct_positivas: { nombre: 'Reseñas positivas', grupo: 'Producto', def: 'Parte de las reseñas con 4 o 5 estrellas.', formula: 'Reseñas de 4–5 ★ ÷ Reseñas', fuente: 'Reseñas', donde: 'Producto' },

  // ------------------------------------------------------------------ Operaciones
  entregados: { nombre: 'Pedidos entregados', grupo: 'Operaciones', def: 'Pedidos en estado entregado.', formula: 'Recuento de pedidos entregados', fuente: 'Pedidos', donde: 'Operaciones' },
  pendientes: { nombre: 'Pedidos pendientes', grupo: 'Operaciones', def: 'Pedidos que aún no se han entregado, cancelado ni devuelto. Un pendiente antiguo suele indicar un pedido atascado.', formula: 'Recuento de pedidos pendientes', fuente: 'Pedidos', donde: 'Operaciones' },
  cancelacion: { nombre: 'Tasa de cancelación', grupo: 'Operaciones', def: 'Proporción de pedidos cancelados sobre el total de pedidos.', formula: 'Pedidos cancelados ÷ Pedidos', fuente: 'Pedidos', donde: 'Operaciones' },
  envio_gratis: { nombre: 'Envío gratuito', grupo: 'Operaciones', def: 'Parte de los pedidos en los que no se cobra envío.', formula: 'Pedidos con envío = 0 ÷ Pedidos', fuente: 'Pedidos', donde: 'Operaciones' },
  coste_envio: { nombre: 'Envío medio cobrado', grupo: 'Operaciones', def: 'Importe medio de envío cobrado por pedido (incluye los pedidos con envío gratuito).', formula: 'Σ envío ÷ Pedidos', fuente: 'Pedidos', donde: 'Operaciones' },

  // ------------------------------------------------------------------ Devoluciones
  dev_pedidos: { nombre: 'Pedidos con devolución', grupo: 'Devoluciones', def: 'Proporción de pedidos entregados o devueltos con alguna devolución. Se divide en devolución total (se devuelve el pedido entero) y parcial (se devuelven algunos productos de un pedido entregado).', formula: '(Pedidos devueltos + Pedidos con devolución parcial) ÷ Pedidos entregados o devueltos', fuente: 'Pedidos, devoluciones', donde: 'Resumen, Operaciones' },
  dev_total: { nombre: 'Pedidos devueltos (totales)', grupo: 'Devoluciones', def: 'Pedidos en estado devuelto: el reembolso iguala el subtotal del pedido.', formula: 'Recuento de pedidos en estado devuelto', fuente: 'Pedidos, devoluciones', donde: 'Operaciones' },
  dev_parcial: { nombre: 'Pedidos con devolución parcial', grupo: 'Devoluciones', def: 'Pedidos entregados con un reembolso que corresponde a uno o varios productos, no al pedido entero.', formula: 'Pedidos entregados con reembolso', fuente: 'Pedidos, devoluciones', donde: 'Operaciones' },
  dev_productos: { nombre: 'Productos devueltos', grupo: 'Devoluciones', def: 'Proporción de unidades devueltas sobre las entregadas. En una devolución parcial las unidades se deducen del importe reembolsado.', formula: 'Unidades devueltas ÷ Unidades de pedidos entregados o devueltos', fuente: 'Líneas, devoluciones', donde: 'Resumen, Operaciones' },
  reembolsado: { nombre: 'Importe reembolsado', grupo: 'Devoluciones', def: 'Dinero devuelto a clientes. Va sin impuestos, por lo que es comparable con las ventas.', formula: 'Σ importe de devoluciones', fuente: 'Devoluciones', donde: 'Operaciones' },

  // ------------------------------------------------------------------ Promociones
  pct_codigo: { nombre: 'Pedidos con código', grupo: 'Promociones', def: 'Parte de los pedidos que usan al menos un código promocional.', formula: 'Pedidos con código ÷ Pedidos', fuente: 'Pedidos, promociones', donde: 'Promociones' },
  ventas_codigo: { nombre: 'Ventas con código', grupo: 'Promociones', def: 'Ventas de los pedidos que usan algún código, contando cada pedido una vez. Los importes no reflejan ningún descuento del código.', formula: 'Σ subtotal de pedidos con código', fuente: 'Pedidos, promociones', donde: 'Promociones' },
  ticket_codigo: { nombre: 'Ticket con código', grupo: 'Promociones', def: 'Ticket medio de los pedidos con código. Se compara con el de los pedidos sin código.', formula: 'Ventas con código ÷ Pedidos con código', fuente: 'Pedidos, promociones', donde: 'Promociones' },
  ticket_sin_codigo: { nombre: 'Ticket sin código', grupo: 'Promociones', def: 'Ticket medio de los pedidos que no usan ningún código.', formula: 'Ventas sin código ÷ Pedidos sin código', fuente: 'Pedidos, promociones', donde: 'Promociones' },
  dos_codigos: { nombre: 'Pedidos con dos o más códigos', grupo: 'Promociones', def: 'Pedidos que acumulan varios códigos. Cuentan en cada código, por lo que la suma por código supera el total.', formula: 'Recuento de pedidos con ≥ 2 códigos', fuente: 'Pedidos, promociones', donde: 'Promociones' },
  pct_lineas_descuento: { nombre: 'Líneas con descuento sobre tarifa', grupo: 'Promociones', def: 'Parte de las líneas vendidas por debajo del precio de catálogo.', formula: 'Líneas con precio < tarifa ÷ Líneas', fuente: 'Líneas de pedido, catálogo', donde: 'Promociones' },
  valor_descuento: { nombre: 'Valor del descuento sobre tarifa', grupo: 'Promociones', def: 'Euros dejados de ingresar frente al precio de catálogo.', formula: 'Σ cantidad × tarifa − Ventas de producto', fuente: 'Líneas de pedido, catálogo', donde: 'Promociones' },
};
